# Generated by Django 5.1.7 on 2025-03-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="transaction",
            name="limit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("MARKET", "Market"),
                    ("LIMIT", "Limit"),
                    ("STOP_LOSS", "Stop-Loss"),
                ],
                default="MARKET",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("EXECUTED", "Executed"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=8,
            ),
        ),
    ]
