# Generated by Django 5.1.7 on 2025-03-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0003_stock_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="portfolio_images/"
            ),
        ),
    ]
