# Generated by Django 5.1.7 on 2025-03-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_app", "0004_portfolio_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="margin_balance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="margin_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="margin_used",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transaction",
            name="strike_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("MARKET", "Market"),
                    ("LIMIT", "Limit"),
                    ("STOP_LOSS", "Stop-Loss"),
                    ("CALL_OPTION", "Call Option"),
                    ("PUT_OPTION", "Put Option"),
                ],
                default="MARKET",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="AlgoStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("condition", models.CharField(max_length=100)),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=False)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_app.portfolio",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_app.stock",
                    ),
                ),
            ],
        ),
    ]
